[package]
authors = ["Matt Ickstadt <mattico8@gmail.com>"]
license = "MIT/Apache-2.0"
name = "elasticlunr-rs"
version = "0.1.0"
description = "A partial port of elasticlunr.js to Rust"
documentation = "https://docs.rs/elasticlunr-rs"
repository = "https://github.com/mattico/elasticlunr-rs"
keywords = ["search", "index", "indexing", "lunr", "elasticlunrjs"]

[lib]
name = "elasticlunr"

[build-dependencies]
phf_codegen = "0.7"

[dev-dependencies]
maplit = "1.0.0"

[dependencies]
lazy_static = "0.2"
phf = "0.7"
rust-stemmers = "1.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
